language: java
jdk:
  - oraclejdk8
after_success:
- ./gradlew jacocoTestReport coveralls


addons:
  coverity_scan:
    project:
      name: "cosminj/java-properties-loader"
      description: "A pure java framework for loading up JSON/PROPERTIES from remote files over over http / classpath / file system."
    notification_email: cosminj@gmail.com
    build_command:   "./gradlew clean build"
    branch_pattern: coverity_scan
